name: MSRM
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.4.2
  - scipy=1.17.0
  - rasterio=1.4.4
  - matplotlib=3.10.8
  - tqdm=4.67.3
  - jupyterlab=4.5.4
  - notebook=7.5.3
  - ipykernel=7.2.0
  - ipywidgets=8.1.8
  - widgetsnbextension=4.0.15
  - jupyterlab_widgets=3.0.16

