name: MSRM
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - rasterio
  - matplotlib
  - tqdm
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets

